version: '3.8'

services:
  php-fpm:
    image: php:8.2-fpm
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    restart: always